# Generated by Django 4.1 on 2022-08-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_type', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pettype',
            name='id',
        ),
        migrations.AlterField(
            model_name='pettype',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
