# Generated by Django 4.1 on 2022-08-30 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_type', '0001_initial'),
        ('pet', '0002_alter_pet_options_alter_pet_picture_alter_pet_raze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet_type.pettype'),
        ),
    ]
