# Generated by Django 4.1 on 2022-08-30 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_type', '0002_remove_pettype_id_alter_pettype_name'),
        ('pet', '0003_alter_pet_type_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type_animal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet_type.pettype'),
        ),
    ]
