# Generated by Django 4.1 on 2022-08-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_alter_pet_type_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type_animal',
            field=models.CharField(max_length=500),
        ),
    ]
