# Generated by Django 4.1 on 2022-09-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vetclient',
            old_name='users',
            new_name='vet_user',
        ),
    ]
